name: Template Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Git hooks
        run: npm run install-hooks
      
      - name: Test protected files system
        run: npm run test:ci
      
      - name: Verify template structure
        run: |
          # Check if required files exist
          for file in ".protected-files.config.js" "TEMPLATE_README.md" "scripts/protect-files.js" "scripts/install-hooks.js" "scripts/test-protection.js" "scripts/setup-template.js" ".git-hooks/pre-commit"; do
            if [ ! -f "$file" ]; then
              echo "❌ Required file not found: $file"
              exit 1
            fi
          done
          
          # Check if required directories exist
          for dir in "docs" ".git-hooks" "scripts" ".github"; do
            if [ ! -d "$dir" ]; then
              echo "❌ Required directory not found: $dir"
              exit 1
            fi
          done
          
          echo "✅ All required files and directories exist"
  
  simulate-template-usage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Simulate template usage
        run: |
          # Create a temporary directory for the test
          mkdir -p /tmp/remy-gh-test
          
          # Copy all files to the test directory
          cp -r ./* /tmp/remy-gh-test/
          cp -r ./.git* /tmp/remy-gh-test/ 2>/dev/null || true
          cp -r ./.protected* /tmp/remy-gh-test/ 2>/dev/null || true
          
          # Navigate to the test directory
          cd /tmp/remy-gh-test
          
          # Initialize a Git repository
          git init
          git config --local user.email "test@example.com"
          git config --local user.name "Test User"
          
          # Rename TEMPLATE_README.md to README.md
          if [ -f "TEMPLATE_README.md" ]; then
            mv TEMPLATE_README.md README.md
          fi
          
          # Install dependencies
          npm install
          
          # Install Git hooks
          npm run install-hooks
          
          # Test the protected files system
          npm run test:ci
          
          echo "✅ Template usage simulation successful"
